parse file and set map, design, and player #3
hyoshie/cub3d pull request #14
Opened 2022-03-07 13:15 UTC by yshima42

## 注意
ファイルから読み込めるようにしたので次からコンパイルする時はmap/simple.cubを読み込んでください。

## 概要
- parseパート（ファイル読み込み、map, design, playerのセット）完了。

## Next
- エラーハンドリング

2022-03-07 15:37 UTC, yshima42 commented
変更してないファイルをまたあげてしまいました。
レビュー前までヘッダーは全部外しても良いかもしれないですね。

2022-03-08 01:10 UTC, hyoshie requested changes
コンパイルエラーの修正お願いします！

2022-03-08 01:10 UTC, hyoshie commented on src/init/init_design.c
> +uint32_t	cub_atoi(char *s)
vmでコンパイルエラーになりました！u_int32_tですね。
```
cc -Wall -Wextra -Werror -g -I./inc -I./lib/minilibx-linux -Ilib/libft -MMD -MP -c src/init/init_design.c -o obj/init_design.o
src/init/init_design.c:70:1: error: unknown type name ‘uint32_t’; did you mean ‘u_int32_t’?
   70 | uint32_t cub_atoi(char *s)
      | ^~~~~~~~
      | u_int32_t
make: *** [Makefile:64: obj/init_design.o] Error 1
```
[対応不要]この書き方も最後に統一した方がいいかも？

2022-03-08 01:10 UTC, hyoshie commented on src/init/parse_file.c
> +	set_map(&game->map, map_lst, num_lines - SEP_LINE);
[対応不要]SEP_LINEって一瞬考えました。別の名前の方がいいかも。
MAP_INFO_ROWSとか思いついたけどスマートじゃないですね。。

2022-03-08 01:41 UTC, yshima42 commented on src/init/init_design.c
> +uint32_t	cub_atoi(char *s)
コンパイルエラー申し訳ないです。一旦intにしました。また統一しましょう！

2022-03-08 01:46 UTC, yshima42 commented on src/init/parse_file.c
> +	set_map(&game->map, map_lst, num_lines - SEP_LINE);
そうなんですよねー、後ほど相談させてください。
このSEP_LINEは最初の8行のdesign用の部分なんですよね。なのでNUM_DESIGN_LINESとかでも良いかもしれないです。また話しましょう。

2022-03-08 04:22 UTC, merged